CREATE DATABASE [rm.urlshortener.dbsql]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'rm.urlshortener.dbsql', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\rm.urlshortener.dbsql.mdf' , SIZE = 4096KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'rm.urlshortener.dbsql_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\rm.urlshortener.dbsql_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET ARITHABORT OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET  DISABLE_BROKER 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET  READ_WRITE 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET RECOVERY FULL 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET  MULTI_USER 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [rm.urlshortener.dbsql] SET DELAYED_DURABILITY = DISABLED 
GO
USE [rm.urlshortener.dbsql]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [rm.urlshortener.dbsql] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
