Use [rm.urlshortener.dbsql]

/* Crate Teable Url */
CREATE TABLE dbo.Url
	(
	Id int NOT NULL IDENTITY (1, 1),
	ShortUrl nvarchar(100) NOT NULL,
	LongUrl nvarchar(4000) NOT NULL,
	CreationDate datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Url ADD CONSTRAINT
	DF_Url_CreationDate DEFAULT getdate() FOR CreationDate
GO
ALTER TABLE dbo.Url ADD CONSTRAINT
	PK_Url PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX IX_ShortUrl ON dbo.Url
	(
	ShortUrl
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/* create Table Stat*/
CREATE TABLE dbo.Stat
	(
	Id int NOT NULL IDENTITY (1, 1),
	UrlId int NOT NULL,
	HitDate datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Stat ADD CONSTRAINT
	DF_Stat_HitDate DEFAULT getdate() FOR HitDate
GO
ALTER TABLE dbo.Stat ADD CONSTRAINT
	PK_Stat PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Stat ADD CONSTRAINT
	FK_Stat_Stat FOREIGN KEY
	(
	Id
	) REFERENCES dbo.Stat
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO