//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rm.urlshortener.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int Id { get; set; }
        public int UrlId { get; set; }
        public System.DateTime HitDate { get; set; }
    
        public virtual Url Url { get; set; }
    }
}
